# This configuration is intended for development purpose, harden in prod
version: '3.8'
services:
  user-app:
    image: user
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://user-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=user
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  user-mongodb:
    image: mongo:4.4.4
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/jhipster/user/mongodb/:/data/db/
