version: '3.8'
services:
  user-mongodb:
    image: mongo:4.4.4
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    command: mongos --configdb csvr/user-mongodb-config --bind_ip 0.0.0.0
  user-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --shardsvr --replSet rs1
  user-mongodb-config:
    image: mongo:4.4.4
    container_name: user-mongodb-config
    command: mongod --configsvr --dbpath /data/db --replSet csvr
