#log level
logging.level.root: ERROR
management:
  endpoint:
    metrics:
      enabled: false

#API documentation path
springdoc.swagger-ui.path: /swagger-ui.html

#Database connection
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

