
logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.relias.smartmatch.user: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: user
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
#Below just kept we will use service mesh for all this
#  sleuth:
#    sampler:
#      probability: 1 # report 100% of traces
#  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
#    base-url: http://localhost:9411
#    enabled: false
#    locator:
#      discovery:
#        enabled: true

server:
  port: 8081
  servlet:
    context-path: /base
